import json
import os
import random

USED_FILE = 'used_posts.json'

# 50 pre-written AITA stories — roterer automatisk
STORIES = [
    {"id":"s01","title":"AITA for not attending my sister's wedding?","body":"So my sister got married last month and I didn't go. Here's why. She's been dating this guy for 3 years and I've always had a bad feeling about him. He's controlling, he constantly checks her phone, and he's made her cut off most of her friends. I told her multiple times I was worried. She told me to mind my business. When the wedding came around, I just couldn't bring myself to celebrate what I think is a toxic relationship. I sent a card and a gift. She hasn't spoken to me since. My parents think I was wrong. Was I the asshole for skipping?"},
    {"id":"s02","title":"AITA for telling my roommate his girlfriend can't stay anymore?","body":"My roommate has been having his girlfriend stay over basically every night for the past two months. We have a two bedroom apartment and I pay half the rent. She doesn't pay anything. She uses the kitchen, the bathroom, leaves her stuff everywhere. I finally snapped last week and told him either she starts contributing to rent or she can't stay over anymore. He called me controlling and said I was trying to run his love life. I just want to live in my own home without a third person living there for free. Am I wrong?"},
    {"id":"s03","title":"AITA for refusing to give my nephew his inheritance early?","body":"My brother passed away two years ago and left his estate to be managed by me until his son turns 25. His son is 22 now and has been asking — actually demanding — that I release the funds early. He wants to invest in some crypto scheme his friend told him about. My brother specifically set up the trust with a delayed release for a reason. His son is furious, says I'm controlling his life, threatened to get a lawyer. I said go ahead. The money is safe where it is. Am I the asshole for following my brother's exact wishes?"},
    {"id":"s04","title":"AITA for not letting my mom use my Netflix account anymore?","body":"I've been paying for Netflix for three years. My mom has been using my account the whole time without paying anything. Last month Netflix started cracking down on password sharing and I got charged extra. I asked my mom to either pay her share or create her own account. She got really upset, said I was being petty over a few dollars, and that family should share. I make decent money but that's not the point. I'm already paying for my own expenses. She ended up calling my aunt to complain about me. AITA?"},
    {"id":"s05","title":"AITA for telling my coworker to stop talking to me during lunch?","body":"I work in an open office and lunch is my only real break from people. I'm pretty introverted and I recharge by being alone. There's one coworker who follows me to the break room every single day and talks nonstop for the entire lunch break. I finally told her nicely that I use lunch to decompress and I'd prefer to eat alone. She went and told our manager I was being antisocial and creating a hostile environment. Now HR wants to talk to me. All I wanted was 30 minutes of peace. Am I the asshole?"},
    {"id":"s06","title":"AITA for kicking my brother out after he ate my kids' birthday cake?","body":"My son turned 8 last week. We had a small party, nothing fancy. My brother came and was drinking a lot. After the kids went to bed, he went into the kitchen and ate more than half the birthday cake that we had saved for my son to take to school for his class the next day. When I found out in the morning I was furious. My brother thought it was funny. I told him to get out and not come back until he apologized to my son. He says I overreacted. My wife thinks I was too harsh. But my son cried. Was I wrong?"},
    {"id":"s07","title":"AITA for not picking up my friend from the airport?","body":"My best friend asked me to pick her up from the airport at 6am on a Tuesday. I have work at 8am and the airport is 45 minutes away. I said I couldn't do it and suggested she take an Uber. She has plenty of money, by the way. She got really upset and said that's what friends are for. Here's the thing — three months ago when I asked her to help me move, she cancelled last minute and I had to hire movers. She never apologized. I feel like the friendship has been one-sided for a while. Am I the asshole for saying no this time?"},
    {"id":"s08","title":"AITA for telling my girlfriend her cooking is bad?","body":"My girlfriend loves to cook and does it almost every night. I appreciate the effort, I really do. But honestly? The food isn't good. It's either underseasoned, overcooked, or just weird combinations that don't work. I've been eating it without complaint for eight months. Last week she asked me directly — and I mean really pushed for an answer — whether I liked her cooking. I finally told her the truth. She's been upset with me for days. My friends are split. Some say honesty is right, others say I should have kept quiet. Was I wrong to tell her the truth when she asked?"},
    {"id":"s09","title":"AITA for telling my parents I won't be home for Christmas?","body":"I'm 26 and I've spent every single Christmas at my parents' house my whole life. This year my girlfriend and I decided to stay home and have our own Christmas together for the first time. My parents acted like I had told them I was never seeing them again. My mom cried on the phone. My dad called it selfish. I offered to visit them the week before Christmas, but that wasn't good enough. I love my parents but I feel like I'm allowed to start my own traditions. I'm an adult. Am I the asshole for wanting to spend the holiday my own way?"},
    {"id":"s10","title":"AITA for refusing to be the designated driver again?","body":"In our friend group I'm the only one who doesn't drink. For two years I've been the default designated driver every single time we go out. Nobody ever asks — they just assume. I've driven people home at 2am, waited for hours at bars, missed plans because I was on call. Last Saturday I said I wasn't available and they should plan for an Uber. Three of them showed up at my house anyway and said it would just be this once. I turned them away. Now the group chat is blowing up saying I abandoned them. Am I the asshole for finally saying no?"},
    {"id":"s11","title":"AITA for not telling my friend her husband is cheating?","body":"I saw my friend's husband at a restaurant with another woman three weeks ago. They were clearly on a date. I've been going back and forth on whether to say anything. My friend seems happy. They have two kids. I don't know if telling her will help or just blow up her life. I talked to my own partner about it and they said I should stay out of it. But the guilt is eating me alive. My friend called me yesterday asking if something was wrong because I've been distant. I almost told her. Am I the asshole if I stay silent?"},
    {"id":"s12","title":"AITA for charging my sister rent when she moved in?","body":"My sister lost her job and asked if she could stay with me for a while. I said yes but told her I'd need her to pay a small amount of rent — just 400 dollars a month, way below market rate. My place is paid off so it would just help cover utilities and food. She was shocked and said family doesn't charge family. She's 34 years old and I know she has savings. I have a mortgage and bills too. She ended up finding another place to stay and now tells people I turned my back on her. Did I do something wrong?"},
    {"id":"s13","title":"AITA for not sharing my lottery winnings with my family?","body":"I won 85 thousand dollars in a scratch-off lottery ticket six months ago. I did not tell my family. I paid off my car, started an emergency fund, and invested the rest. Last week my cousin somehow found out and told everyone. Now my parents, siblings, and various relatives are all asking for money. Some are saying I'm selfish. One uncle said I have a moral obligation to help family. I worked hard to be in a stable financial position and one lucky ticket doesn't mean I owe anyone anything. Am I the asshole for keeping it private and keeping it for myself?"},
    {"id":"s14","title":"AITA for correcting my boss in a meeting?","body":"My boss has been making a factual error in our team meetings for weeks. He keeps citing a statistic that I know for a fact is wrong — I researched it personally for a project last year. Last Tuesday I gently corrected him in front of the team by saying I had seen different numbers and offered to send the source. He went quiet and moved on. After the meeting he pulled me aside and said it was unprofessional to correct him publicly. I thought I was helping the team make better decisions with accurate information. Was I wrong to speak up?"},
    {"id":"s15","title":"AITA for not inviting my stepsister to my bachelorette party?","body":"I'm getting married in two months. My stepsister and I have never been close. Our parents married when we were both in college and we've always been polite but not really friends. I planned my bachelorette weekend with my actual close friends — people I've known for years. When my stepsister found out she wasn't invited she told my stepdad, who told my mom, who called me upset. Everyone is acting like I committed a crime. I didn't invite every female relative I have. I invited my real friends. Am I the asshole for that?"},
    {"id":"s16","title":"AITA for taking the last piece of pizza?","body":"This sounds small but it caused a huge argument. My partner and I ordered pizza. We each had a few slices. There was one piece left. I asked if they wanted it, they said no, so I ate it. Twenty minutes later they wanted it and were genuinely upset that I'd eaten it. I reminded them they said no. They said I should have known they'd change their mind. Now they're calling me selfish over a single slice of pizza. We've been together three years and this is not the first time something small has blown up. Am I the asshole for eating the pizza I asked permission for?"},
    {"id":"s17","title":"AITA for ending a friendship over a cancelled plan?","body":"My friend has cancelled plans on me 7 times in the last year. Always last minute, always with a different excuse. I've rearranged my schedule, turned down other plans, and been let down every single time. Last month I bought tickets to a concert for both of us. Non-refundable. She cancelled the day before. I went alone. When I got home I sent her a message saying I think we've grown apart and I'm stepping back from the friendship. She's devastated and says I'm overreacting to one cancellation. I didn't tell her I'd been counting. Was I wrong?"},
    {"id":"s18","title":"AITA for telling my mom I don't want her advice anymore?","body":"My mom gives advice on everything. What I eat, how I dress, my relationship, my career choices, my home decor. I'm 29 years old. Last month I redecorated my living room and she spent an entire visit telling me everything she would have done differently. I finally snapped and told her I love her but I need her to stop giving unsolicited advice. She cried and said she was just trying to help. My dad called me the next day and said I hurt her feelings badly. I feel guilty but also like I had to say something. Am I the asshole?"},
    {"id":"s19","title":"AITA for not letting my dog meet my girlfriend's cat?","body":"My girlfriend and I have been together for eight months. She has a cat, I have a dog. She's been pushing for us to introduce them, saying it's a big step for our relationship. My dog is friendly but large and has a high prey drive. I've seen him react badly to cats before. I don't think the introduction is safe and I've said no until we can do it with a professional trainer present. She thinks I'm being overprotective and that it would be fine. I just don't want anyone to get hurt. Am I the asshole for putting my foot down?"},
    {"id":"s20","title":"AITA for not finishing my bridesmaid duties?","body":"I was a bridesmaid for my college friend's wedding. I helped with the planning, attended every shower and event, and spent over a thousand dollars on dresses, travel, and gifts. Two weeks before the wedding, she called to tell me she was replacing me as maid of honor with her cousin because her family was pressuring her. I said I understood but told her I wouldn't be able to continue as a bridesmaid either. She was shocked. I wasn't angry, I just felt like the relationship had changed. She's been telling mutual friends I abandoned her before her wedding. Was I wrong?"},
    {"id":"s21","title":"AITA for telling my partner I don't want kids?","body":"I'm 31 and my partner is 29. We've been together for four years. I have always said I don't want children. My partner said the same thing when we met. Last month they told me they had changed their mind and actually do want kids now. I said I hadn't changed my mind. They're saying I'm being selfish and inflexible. I feel like I've been consistent the entire relationship. I love them but this feels like a dealbreaker for both of us. They want me to at least consider it. I've considered it for 31 years. Am I the asshole for not changing my mind?"},
    {"id":"s22","title":"AITA for not giving up my seat on the plane?","body":"I paid extra for a window seat on a four hour flight. A family boarded late and a woman asked me to move to a middle seat so her family could sit together. I said no. I specifically chose and paid for that seat. She kept pushing, saying her child needed to be next to her. The child looked about 10 years old, not a toddler. A flight attendant came over and I explained that I had paid for the seat. The attendant said it was my right to stay. The family had to split up. I got dirty looks for the whole flight. Was I wrong to keep my seat?"},
    {"id":"s23","title":"AITA for leaving a bad review for my friend's business?","body":"My friend started a cleaning business last year. I was one of her first clients and I supported her from the start. The last two times she came, the cleaning was genuinely bad — surfaces left dirty, things moved and not put back, one item broken. I asked her to address it and she got defensive. I ended up leaving an honest review online explaining my experience. She found out and was devastated, saying I betrayed her as a friend. I feel like if I hadn't been honest, she wouldn't know she had a real problem with her service. Was I wrong?"},
    {"id":"s24","title":"AITA for not helping pay for my parents' vacation?","body":"My parents want to take a family vacation and asked all three adult kids to chip in. My two siblings agreed right away. I said no. Here's why — last year I was going through a rough financial period and asked my parents for a small loan. They said they didn't have the money. Two weeks later they went on a cruise. I never forgot that. I'm not being petty, I just don't feel the same sense of obligation I used to. I told them I'd join if they covered me, but I wouldn't contribute. My siblings think I'm holding a grudge. Am I the asshole?"},
    {"id":"s25","title":"AITA for telling my friend their baby isn't cute?","body":"My friend had a baby three months ago. Every time we talk she asks me to confirm how beautiful her baby is. I've been saying nice vague things like she looks healthy or she seems happy. Last week she pushed really hard and asked me directly — do you think she's the cutest baby you've ever seen? I said honestly, I think all babies look alike to me and beauty is hard to judge at this age. She burst into tears and hasn't replied to my messages since. I thought honesty was better than fake compliments. Was I the asshole for not just lying?"},
    {"id":"s26","title":"AITA for refusing to work overtime without extra pay?","body":"My company has been going through a busy period and my manager has been asking everyone to work extra hours. Unpaid. They called it team dedication. I said I'm happy to work overtime but I expect to be compensated. My manager said everyone else was doing it without complaint. I said that was their choice. I work my contracted hours and I do them well. I'm not giving away my time for free. My coworkers are now annoyed because they feel pressured to stay late since I'm leaving on time. Am I the asshole for holding my boundary?"},
    {"id":"s27","title":"AITA for eating my coworker's lunch?","body":"Okay before you judge me — I didn't know it was their lunch. There was food in the fridge with no name on it and I was starving. I ate it. Turns out it belonged to my coworker who had brought leftovers from a birthday dinner. She was really upset. I apologized and offered to buy her lunch that day. She accepted but has been cold with me ever since and mentioned it to other coworkers. I feel bad but I also think the situation would have been avoided if she'd labelled her food. Am I still the asshole?"},
    {"id":"s28","title":"AITA for not lending my car to my brother?","body":"My brother asked to borrow my car for a weekend trip. I said no. Why? Because the last time I lent him my car, two years ago, he returned it with a dent he didn't mention until I noticed it. He paid for repairs eventually but it took months of asking. He says that was the past and I should let it go. I said I forgave him but I also learned from it. He's now telling the family I'm being spiteful. My parents are saying I should trust family. But trust is earned, right? Am I the asshole for saying no?"},
    {"id":"s29","title":"AITA for not clapping at my cousin's graduation?","body":"My cousin graduated from a two-year online certificate program. My whole family treated it like she had graduated from Harvard. There was a huge party, speeches, the works. When they asked everyone to clap and cheer, I clapped politely but didn't go over the top. My aunt noticed and later pulled me aside to say I was being dismissive. I wasn't trying to be mean. I just feel like the reaction was disproportionate. I have a four-year degree and got a dinner. Am I the asshole for not performing enthusiasm I didn't feel?"},
    {"id":"s30","title":"AITA for telling my partner to clean up after themselves?","body":"I am a neat person. My partner is not. When we moved in together a year ago I thought we'd find a balance. Instead I've been doing most of the cleaning while their mess spreads. Dishes left out, clothes on the floor, bathroom left dirty. I've mentioned it many times. Last week I hit my limit and said that if things don't change I can't continue living together. They said I was making them feel like a bad person just for how they naturally are. I said I wasn't judging them but I can't live in clutter. Am I the asshole for making it a serious issue?"},
    {"id":"s31","title":"AITA for telling my friend group what really happened?","body":"For months my friend group believed a certain narrative about why our friend Sarah left the group. The story going around was that she just drifted away. The truth is she was asked to leave after some serious issues with dishonesty that most of the group doesn't know about. Last week someone was planning to reconnect with her and I told them the real reason she left. Now half the group thinks I should have kept quiet and let the past be the past. The other half thanks me. Was I wrong to tell the truth?"},
    {"id":"s32","title":"AITA for not celebrating my work anniversary with my team?","body":"My company loves making a big deal out of work anniversaries. When mine came up this year, my manager wanted to do the usual thing — announce it in the all-hands meeting, get a cake, have everyone clap. I emailed her privately and asked to skip it. I hate being the center of attention and it makes me deeply uncomfortable. She was surprised but agreed. Some coworkers found out and think I was being antisocial or that I think I'm above team traditions. I just have genuine social anxiety about those moments. Am I the asshole?"},
    {"id":"s33","title":"AITA for uninviting my dad's girlfriend from our family photo?","body":"My parents divorced five years ago. My dad has been dating someone new for about a year. We were doing a family photo for the holidays and my dad assumed his girlfriend would be included. I said I'd prefer it to be just immediate family — meaning me, my siblings, and our parents. My mom would have been uncomfortable and honestly so would I. Dad got upset and said I was being unwelcoming. I said it wasn't personal to her, I just wanted the photo to be family only. He's still annoyed. Am I wrong for wanting that boundary?"},
    {"id":"s34","title":"AITA for not sharing my inheritance with my siblings?","body":"My grandmother passed away last year and left me a specific amount of money in her will. She did not leave the same to my siblings. This was her choice — she and I had a very close relationship for many years and she told me before she died that this was intentional. My siblings are saying it's not fair and that I should split it evenly. I said grandma made her wishes clear and I'm going to respect them. They're calling me greedy. I feel like going against her wishes would actually be disrespectful to her. Am I the asshole for keeping what she left me?"},
    {"id":"s35","title":"AITA for blocking my ex on everything after we broke up?","body":"My ex and I broke up three months ago. It was mutual but painful. Right after, I blocked them on every platform. Not out of anger — I just know myself and I know that seeing their posts and updates would make it harder for me to heal. My ex found out through a mutual friend and was really hurt. They said blocking is aggressive and implies they did something wrong. I explained it was for my own mental health, not a statement about them. They told people I was being dramatic. Was I wrong to do what I needed to do to move on?"},
    {"id":"s36","title":"AITA for not giving my seat to a pregnant woman?","body":"I was on the subway after a really long day. I'd been on my feet for 9 hours. I finally got a seat. At the next stop a visibly pregnant woman got on. Nobody else moved. I considered it but I genuinely felt like I might faint if I stood up — I hadn't eaten, I was exhausted, and I have a condition that affects my balance. I stayed seated. She didn't ask me specifically but made a point to sigh loudly near me. Someone called me out at the next stop. I felt terrible but I was also struggling. Am I the asshole?"},
    {"id":"s37","title":"AITA for throwing away my partner's old clothes?","body":"My partner has clothes they haven't worn in years taking up most of the closet. I've asked multiple times if we could sort through them. They always say yes and never do it. Last month while they were away for work I went through the pile and donated everything that still had tags on it or hadn't been worn in what I estimated was over two years. When they came back they were furious. Some of the items had sentimental value I didn't know about. I feel terrible about that but I also felt like I had no other option. Was I wrong?"},
    {"id":"s38","title":"AITA for telling my friend her boyfriend is using her?","body":"My friend has been dating someone for six months. In that time he has borrowed money three separate times and paid back none of it. He doesn't have a job but also doesn't seem to be looking for one. She pays for everything when they go out. She seems happy though. Last week she mentioned he was asking for another loan and I finally said what I've been thinking — I think he's using you. She got really defensive and said I was jealous and unsupportive. We haven't talked since. Was I wrong to say something?"},
    {"id":"s39","title":"AITA for not paying for my friend's meal after they ordered the most expensive thing?","body":"A group of us went out to dinner and said we'd split the bill evenly. But one friend ordered two appetizers, the most expensive entree, and two cocktails. Everyone else had one course and water or one drink. When the bill came and we split it, I ended up paying for way more than I ate. I said I'd rather pay for what I ordered and pulled out my portion. My friend was embarrassed. The others looked uncomfortable. I don't think even splitting is fair when the orders are that different. Am I the asshole?"},
    {"id":"s40","title":"AITA for telling my sister her parenting style is too strict?","body":"My sister has two kids, ages 8 and 10. She runs a very rigid household — no screen time, specific bedtimes, structured activities, very little free play. When the kids visit me they seem almost anxious to relax and have fun. Last week my sister asked what I thought about her parenting approach and I was honest. I said I worried the kids didn't have enough space to just be kids. She was furious and said I had no right to comment since I don't have children. We haven't spoken since. She asked for my opinion though. Was I wrong to give it?"},
    {"id":"s41","title":"AITA for refusing to babysit for free anymore?","body":"I have been babysitting for my neighbor for two years. At first it was occasional and I didn't mind. Then it became almost every weekend, sometimes weekday evenings too. I was never paid. I was told it was a favor between neighbors. I like the kids but this has become a second job. When I told my neighbor I couldn't do it anymore without some compensation she said I was being materialistic and that I was like family. Being treated like family would mean being asked, not assumed. I said no more free sitting. She told other neighbors I was being difficult. AITA?"},
    {"id":"s42","title":"AITA for not pretending to like my stepmom?","body":"My dad remarried when I was 16. I'm 24 now. I've never clicked with my stepmom. She's not a bad person, we're just completely different. My dad has always pushed me to act closer to her than I actually feel. At a family dinner recently he asked me to refer to her as family in front of his in-laws. I said I was happy to be polite but I wasn't comfortable calling someone family when that's not how I feel. My dad was embarrassed. My stepmom looked hurt. I didn't say anything mean, I just didn't perform a closeness that doesn't exist. Was I wrong?"},
    {"id":"s43","title":"AITA for telling my partner I need alone time every day?","body":"I'm an introvert and I need alone time to function. My partner is an extrovert and gets energy from being together. We moved in a year ago and I've struggled more than I expected. I finally told them I need at least one hour of alone time every evening — no talking, no shared activities, just solo time. They felt rejected and said it seemed like I didn't want to be with them. I explained it has nothing to do with how much I love them, it's just how I'm wired. They're trying to understand but it's been tense. Am I asking for too much?"},
    {"id":"s44","title":"AITA for not telling my friend I got a promotion?","body":"I got promoted at work two months ago. My salary went up significantly. I didn't tell my close friend because she's been struggling to find a job for almost a year and I didn't want to make her feel worse. She found out through someone else last week and was hurt that I didn't tell her. She said she wanted to celebrate with me and that by hiding it I treated her like she was fragile. I was trying to be sensitive. She felt excluded. I genuinely didn't know which choice was right. Was I the asshole for keeping it from her?"},
    {"id":"s45","title":"AITA for leaving my own surprise party?","body":"My friends threw me a surprise party. I walked in, saw everyone, felt completely overwhelmed and anxious, stayed for about 45 minutes, and then made an excuse and went home. I have social anxiety and large groups are very hard for me even with people I love. My friends were hurt and confused. One said she spent weeks organizing it. I feel terrible but I also genuinely couldn't stay. I've talked to them since and some understand, some don't. One friend said I was being ungrateful. Was I the asshole for leaving my own party?"},
    {"id":"s46","title":"AITA for telling my parents I won't visit for every holiday?","body":"I live four hours from my parents. For years I've driven to see them for every holiday — Christmas, Thanksgiving, Easter, birthdays, Mother's Day, Father's Day. It's exhausting and expensive. This year I told them I'd come for two major holidays and we'd video call for the rest. My mom said I was abandoning the family. My dad said I was being selfish. I'm 32 years old with my own life, my own expenses, and limited vacation days. I still want to see them, just not every single time. Am I the asshole for setting this limit?"},
    {"id":"s47","title":"AITA for not lending money to my best friend?","body":"My best friend asked to borrow 2000 dollars for rent. He's in a tough spot after losing his job. I have the money. But three years ago I lent him 800 dollars that he never paid back. He never acknowledged it or offered to repay it. We never talked about it and I let it go because of the friendship. This time I said I couldn't help financially. He was shocked and hurt. I didn't tell him why because I didn't want to bring up old history. Now he thinks I just don't care. I do care. I just can't afford to lose money again. Am I wrong?"},
    {"id":"s48","title":"AITA for correcting someone's grammar in a text?","body":"I know this sounds petty. My coworker sends group texts full of grammatical errors — your instead of you're, there instead of their, stuff like that. Last week he sent one that was genuinely confusing because of the errors and I replied correcting it so everyone understood what he meant. He was embarrassed and told me later it was rude. I said I was just trying to clarify the message. Nobody else said anything but I could tell a few people agreed with him from the silence. It wasn't meant as an attack, just a correction. Was I the asshole?"},
    {"id":"s49","title":"AITA for not giving my sister my old phone?","body":"I upgraded my phone and my sister found out. She immediately said I should give her my old one since she needed a new phone. I had already sold it online. She was upset and said I should have offered it to her first. We're not especially close and it never crossed my mind. She's saying I was selfish because she's family. I mean, it was my phone and my money. I didn't know she needed one. She never mentioned it. Am I the asshole for selling it to a stranger instead of giving it to her?"},
    {"id":"s50","title":"AITA for asking my guest to leave after they criticized my home?","body":"I had a friend over for dinner — first time at my place. Within the first ten minutes she made comments about my furniture being outdated, my kitchen being small, and my neighborhood being loud. I've worked really hard to afford my apartment and I'm proud of it. After the third comment I said I thought it was best if she left, that I clearly wasn't in a position to host her comfortably. She was shocked and left. She's been telling people I kicked her out for no reason. I don't feel like I have to sit in my own home and hear it criticized. Was I wrong?"},
]

def load_used():
    if os.path.exists(USED_FILE):
        with open(USED_FILE) as f:
            return json.load(f)
    return []

def save_used(used):
    with open(USED_FILE, 'w') as f:
        json.dump(used[-50:], f)

def pick_random_story(timeframe='week'):
    used = load_used()
    available = [s for s in STORIES if s['id'] not in used]
    
    if not available:
        # Reset og start på nytt
        used = []
        available = STORIES
    
    chosen = random.choice(available)
    used.append(chosen['id'])
    save_used(used)
    
    print(f"Story: {chosen['title']}")
    print(f"Words: {len(chosen['body'].split())}")
    
    return {
        'id': chosen['id'],
        'title': chosen['title'],
        'body': chosen['body'],
        'score': 0,
        'url': 'https://reddit.com/r/AmItheAsshole'
    }

if __name__ == '__main__':
    story = pick_random_story()
    print(json.dumps(story, indent=2)[:300])
